### ISSUE TITLE
[Profession]Skinning

### ISSUE THREAD

**Issue by Senjah** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#286]
**Describe the bug**
After learning the skinning proffesion from trainer if you log out the profession is gone 
Doesnt work with other professions only with skinning
**To Reproduce**
Simply Learn the skinning log out
and the profession is gone

**Comment by Duff-SPP** [comment]
I dont know how this happend to you, iv tested this now on my end wich is the same DB. And i dont have this issue, iv tested undead rogue and human paladin. when i relog the issue isnt here :)

i can relog as many times as i want and i still have the Proffesion Skinning 👍 

Imma close this one, please reopen if the issue is still there.
