### ISSUE TITLE
[Quest]The Serpent's Heart quest zone

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#352]
Area is instanced already with broken jade statue.

![image](https://user-images.githubusercontent.com/71927836/97551932-9238ea80-1a0e-11eb-9150-aa9f0fc8d46a.png)

https://www.wowhead.com/quest=29931/the-serpents-heart

**Comment by Duff-SPP** [comment]
i dont really understand the issue here?.. only thing i could think about would be if you refered to the state of the statue in MOP :). Since we are in Legion the maps and area's have changed. we are not able to put it back to its state on MOP before it broke :D. idk if this is the issue?

but please dm me
