### ISSUE TITLE
Issues with class order hall questline

### ISSUE THREAD

**Issue by Friendless123** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#721]
**Describe the bug**
i have noticed one issue though the paladin class hall on aroura the mission table is bugged it gives me the quest "dark storms" but when i click on the table it doesn't show up. and in my quest log it shows it as a death knight class hall quest.

**To Reproduce**
1. paladin order hall after finishing artefact quest and receive first mission table quest
2. check mission table
3. check quest log see quest "dark storms" listed as Death Knight order hall quest
4. Be paladin and make sad face. :[

**Expected behavior**
I expected to be able to use the mission table to send my followers on the quest. but cannot because it doesn't appear.

**Comment by Serithul** [comment]
If you can't use the mission table properly it's most likely due to you not having a garrison built. It's a known byproduct of the garrison-class hall script (because it's shared). In order to use the mission table properly, you need to have a garrison built and at least one follower on it obtained.

As per the quest, if i remember correctly from a ticket I resolved some time ago, it's just a visual bug, whilst the quest is the right one. I'm not entirely sure though so please feel free to correct me on this one. I do remember the Death Knight one actually has an objective that says to recruit Ghouls or something, so that should be an indicator to check.

For the Garrison, I'll be more than happy to provide you a Garrison Skip Scroll if you open a ticket in our discord server so you won't have to go through the whole process!

**Comment by acidmanifesto** [comment]
Can not seem to replicate the issue at this time. Please let us know if the issue arises again.
